// todo double check sonarqube config, see devops tools for sonarqube setup 
// https://github.com/bcgov/nr-showcase-devops-tools/tree/master/tools
// (bcgovimages/sonarqube:6.7.5) use image, don't need to build
// todo setup sonarqube server in our tools namespace
// change the password immediately, store in secrets

// todo get these podTemplates from templates folder?
def sonarqubePodLabel = "eagle-public-${UUID.randomUUID().toString()}"
// podTemplate(label: sonarqubePodLabel, name: sonarqubePodLabel, serviceAccount: 'jenkins', cloud: 'openshift', containers: [])

@NonCPS
import groovy.json.JsonOutput
/*
 * Sends a rocket chat notification
 */
def notifyRocketChat(text, url) {
    def rocketChatURL = url
    def payload = JsonOutput.toJson([
      "username":"Jenkins",
      "icon_url":"https://wiki.jenkins.io/download/attachments/2916393/headshot.png",
      "text": text
    ])

    sh("curl -X POST -H 'Content-Type: application/json' --data \'${payload}\' ${rocketChatURL}")
}

/*
 * Updates the global pastBuilds array: it will iterate recursively
 * and add all the builds prior to the current one that had a result
 * different than 'SUCCESS'.
 */
def buildsSinceLastSuccess(previousBuild, build) {
  if ((build != null) && (build.result != 'SUCCESS')) {
    pastBuilds.add(build)
    buildsSinceLastSuccess(pastBuilds, build.getPreviousBuild())
  }
}

/*
 * Generates a string containing all the commit messages from
 * the builds in pastBuilds.
 */
@NonCPS
def getChangeLog(pastBuilds) {
  def log = ""
  for (int x = 0; x < pastBuilds.size(); x++) {
    for (int i = 0; i < pastBuilds[x].changeSets.size(); i++) {
      def entries = pastBuilds[x].changeSets[i].items
      for (int j = 0; j < entries.length; j++) {
        def entry = entries[j]
        log += "* ${entry.msg} by ${entry.author} \n"
      }
    }
  }
  return log;
}

def CHANGELOG = "No new changes"
def IMAGE_HASH = "latest"

pipeline {
  agent none
  environment {
    ROCKET_QA_WEBHOOK = credentials('rocket-qa-webhook') // todo not sure jenkins credentials here will get the openshift secrets, may need to keep as script step
    ROCKET_DEPLOY_WEBHOOK = credentials('rocket-deploy-webhook')
  }
  options {
    disableResume()
  }
  stages {
    stage('Build') {
      agent { label 'build' }
      steps {
        script {
          pastBuilds = []
          buildsSinceLastSuccess(pastBuilds, currentBuild);
          CHANGELOG = getChangeLog(pastBuilds);

          echo ">>>>>>Changelog: \n ${CHANGELOG}"

          try {
            echo "Building eagle-public develop branch"
            openshiftBuild bldCfg: 'eagle-public-angular', showBuildLogs: 'true'

            echo "Build done"

            echo ">>> Get Image Hash"
            // Don't tag with BUILD_ID so the pruner can do it's job; it won't delete tagged images.
            // Tag the images for deployment based on the image's hash
            IMAGE_HASH = sh (
              script: """oc get istag eagle-public:latest -o template --template=\"{{.image.dockerImageReference}}\"|awk -F \":\" \'{print \$3}\'""",
              returnStdout: true).trim()
            echo ">> IMAGE_HASH: ${IMAGE_HASH}"
          } catch (error) {
            notifyRocketChat(
              "The latest build of eagle-public seems to be broken. \n Error: \n ${error}",
              ROCKET_QA_WEBHOOK
            )
            throw error
          }
        }
      }
    }

    stage('Unit Tests') {
      agent { label 'unit-tests' }
      steps {
        script {
          echo "Placeholder - Running unit-tests"
        }
      }
    }

    stage('exeucte sonar') {
      agent { label 'sonarqubePodLabel' }
      environment {
        // set to whatever the secret name is
        SONARQUBE_URL = credentials('url')
      }
      steps {
        checkout scm
        dir('sonar-runner') {
          try {
            // todo update url
            sh './gradlew sonarqube -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.verbose=true --stacktrace --info'
          } finally {
            echo "Scan complete"
          }
        }
      }
    }

    stage('Deploy to test'){
      steps {
        script {
          try {
            echo "Deploying to test..."
            openshiftTag destStream: 'eagle-public-test', verbose: 'false', destTag: 'test', srcStream: 'eagle-public-test', srcTag: "${IMAGE_HASH}"
            sleep 5
            // todo eagle-test? what depCfg?
            openshiftVerifyDeployment depCfg: 'eagle-public-build', namespace: 'eagle-test', replicaCount: 1, verbose: 'false', verifyReplicaCount: 'false', waitTime: 600000
            echo ">>>> Deployment Complete"

            notifyRocketChat(
              "A new version of eagle-public is now in Test. \n Changes: \n ${CHANGELOG}",
              ROCKET_DEPLOY_WEBHOOK
            )

            notifyRocketChat(
              "A new version of eagle-public is now in Test and ready for QA. \n Changes to test: \n ${CHANGELOG}",
              ROCKET_QA_WEBHOOK
            )
          } catch (error) {
            notifyRocketChat(
              "The latest deployment of eagle-public to Test seems to have failed\n'${error.message}'",
              ROCKET_DEPLOY_WEBHOOK
            )
            error('Deploy failed')
          }
        }
      }
    }
  }
}
